node_radius = 30
background_color = "white"
node_color = "#ccccff"
hightlight = "red"
hightlight_text = "white"
text_color = "black"
line_color = "black"
font_size = 20
window_width = 1080
window_height = 720
x_padding = 150
y_padding = node_radius * 4 + 5
maxDepth = 4
maxValue = 100
minValue = 0
animation_delay = 0.5